server:
  port: 8041
  tomcat:
    accesslog:
      enabled: true
    basedir: log/tomcat

spring:
  application:
    name: lsm-user
  web:
    resources:
      add-mappings: false
    locale: en_EN
    locale-resolver: fixed
  datasource:
    username: lsm_user
  liquibase:
    change-log: db/changelog/changelog.yml
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

management:
  endpoints:
    web:
      base-path: /manage
  endpoint:
    metrics:
      enabled: true

jwt:
  token-expiration: 20m
  refresh-token-expiration: 1h

cache:
  stores:
    jwt-blacklist:
      mode: REPLICATED
      expiration: ${jwt.token-expiration}
  communication-port: 47100
  discovery-port: 47500
